spring.application.name=petsale
spring.datasource.url=jdbc:mysql://localhost:3306/pet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.secret=petsale-secret-key-for-jwt-authentication-2026
# Thông tin cấu hình Cloudflare R2
cloudflare.r2.access-key=6198d59012c7b9987cd810b38a514c9c
cloudflare.r2.secret-key=78d0d3f6570cf816b1517704b72966043ba4333522d4504612b8b7ccc8c0388f
# Cloudflare Account ID lấy trên trang chủ Cloudflare R2
cloudflare.r2.endpoint=https://58fc6d9a464274120a5fd19ede3008c5.r2.cloudflarestorage.com
cloudflare.r2.region=auto
cloudflare.r2.bucket-name=pet-images-bucket
# Dùng để lưu trực tiếp vào db ở field image_url
cloudflare.r2.public-url=https://pub-xxxxxxxxxx.r2.dev
