spring.application.name=registry-service

# Port chạy service
server.port=8081

# MongoDB connection (connection string = chuỗi kết nối)
spring.data.mongodb.uri=mongodb://root:12345678@localhost:27017/registry_db?authSource=admin
# (optional) log để debug query
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
jwt.secret=petsale-secret-key-for-jwt-authentication-2026
